### ISSUE TITLE
A typo in the code.

### ISSUE THREAD

**Issue by wdkkkk** [coltonstearns/dynamic-gaussian-marbles#7]
Hi @coltonstearns. It looks like there's a mistake in the code because the segmentation is in the third channel of properties (i.e., properties[:, 3]). Could you please check it?
```
        # reorder points by segmentation
        segmentation_reordering = torch.argsort(properties[:, 7])
        properties = properties[segmentation_reordering]
```
https://github.com/coltonstearns/dynamic-gaussian-marbles/blob/b06684920779cb3bc2841ede4745c067c814e000/src/models/sequence.py#L85C1-L87C57

**Comment by coltonstearns** [comment]
Yes that's a bug, thank you for finding it! Fortunately, I don't think the ordering of the properties has any effect in the current version of the code (this was only used in a previous implementation) - however, I'll update this to avoid confusion :)

**Comment by wdkkkk** [comment]
Thanks for your efforts!
